# Generated by Django 6.0.3 on 2026-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True, verbose_name='ID заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает сборки'), ('processing', 'В процессе сборки'), ('done', 'Собран')], default='pending', max_length=20, verbose_name='Статус сборки')),
                ('order_data', models.JSONField(default=dict, verbose_name='Данные заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задание на сборку',
                'verbose_name_plural': 'Задания на сборку',
            },
        ),
    ]
