# Generated by Django 6.0.3 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20),
        ),
    ]
