# Generated by Django 6.0.3 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_text',
            field=models.TextField(blank=True, verbose_name='Текст ошибки'),
        ),
    ]
