# Generated by Django 6.0.3 on 2026-04-22 10:58

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/product_images/', verbose_name='Изображение товара')),
                ('alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/', verbose_name='Изображение категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('ordering_index', models.IntegerField(default=0, verbose_name='Индекс сортировки')),
                ('parent', models.ForeignKey(blank=True, help_text='Возможны подкатегории от главной категории товаров (макс 2 уровня)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='Главная категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['ordering_index', 'title'],
            },
            bases=(catalog.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('count', models.IntegerField(default=0, verbose_name='Наличие на складе')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки товара')),
                ('description', models.TextField(max_length=255, verbose_name='Краткое описание товара')),
                ('full_description', models.TextField(blank=True, max_length=500, verbose_name='Полное описание товара')),
                ('free_delivery', models.BooleanField(default=True, verbose_name='Бесплатная доставка')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг товара')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_limited', models.BooleanField(default=False, help_text='В Limited edition попадают до 16 товаров с галочкой Ограниченный тираж', verbose_name='Ограниченный тираж')),
                ('ordering_index', models.IntegerField(db_index=True, default=0, help_text='В каталог топ-товаров попадают 8 первых товаров по параметру индекс сортировки', verbose_name='Индекс сортировки')),
                ('purchase_count', models.IntegerField(db_index=True, default=0, help_text='Товары сортируются по популярности', verbose_name='Количество покупок')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('images', models.ManyToManyField(blank=True, to='catalog.productimage')),
                ('specifications', models.ManyToManyField(blank=True, to='catalog.specification')),
                ('tags', models.ManyToManyField(blank=True, to='catalog.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-ordering_index', '-purchase_count'],
            },
            bases=(catalog.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Отзыв покупателя')),
                ('rate', models.PositiveSmallIntegerField(verbose_name='Оценка пользователя (от 1 до 5 включительно)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_users.profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
