# Generated by Django 6.0.3 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordering_index',
            field=models.IntegerField(db_index=True, default=0, help_text='В каталог топ-товаров-8 первых товаров по индексу сортировки', verbose_name='Индекс сортировки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка пользователя (от 1 до 5 вкл.)'),
        ),
    ]
