# Generated by Django 6.0.3 on 2026-04-29 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('free', 'Бесплатная доставка'), ('express', 'Экспресс доставка'), ('ordinary', 'Обычная доставка')], default='free', max_length=100, verbose_name='Тип доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('online', 'Онлайн картой'), ('card', 'Карта курьеру'), ('someone', 'Онлайн со случайного чужого счета')], default='online', max_length=100, verbose_name='Тип оплаты')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='created', max_length=100, verbose_name='Статус заказа')),
                ('city', models.CharField(max_length=100, verbose_name='Город доставки')),
                ('address_delivery', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_users.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент покупки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderItem', to='catalog.product', verbose_name='Товары в заказе'),
        ),
    ]
