# Generated by Django 6.0.3 on 2026-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_deleted_at_order_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета')], default='online', max_length=100, verbose_name='Тип оплаты'),
        ),
    ]
