# Generated by Django 6.0.3 on 2026-05-12 09:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_add_required_data'),
        ('catalog', '0003_alter_product_ordering_index_alter_review_rate'),
        ('order', '0003_alter_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_delivery_price', models.DecimalField(decimal_places=2, default=Decimal('2.67'), max_digits=10, verbose_name='Стоимость обычной доставки (при сумме < порога)')),
                ('free_threshold_for_ordinary_delivery', models.DecimalField(decimal_places=2, default=Decimal('26.67'), max_digits=10, verbose_name='Порог бесплатной обычной доставки')),
                ('express_delivery_price', models.DecimalField(decimal_places=2, default=Decimal('6.67'), max_digits=10, verbose_name='Стоимость экспресс-доставки')),
            ],
            options={
                'verbose_name': 'Расходы на доставку',
                'verbose_name_plural': 'Расходы на доставку',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_users.profile', verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_order_status_b4d09f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['profile', 'status'], name='order_order_profile_aefa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session_key', 'status'], name='order_order_session_a1dee7_idx'),
        ),
    ]
