# Generated by Django 6.0.3 on 2026-05-09 12:23
from django.db import migrations

def add_required_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Создаём группы
    groups = ['Менеджер', 'Клиент', 'Продавцы']
    for name in groups:
        Group.objects.get_or_create(name=name)

    # Получаем или создаём ContentType для моделей catalog.Product, catalog.Category, order.Order
    # Используем get_or_create, чтобы не дублировать, если права уже созданы Django позже
    ct_product, _ = ContentType.objects.get_or_create(app_label='catalog', model='product')
    ct_category, _ = ContentType.objects.get_or_create(app_label='catalog', model='category')
    ct_order, _ = ContentType.objects.get_or_create(app_label='order', model='order')

    # Создаём нужные права (если их нет)
    permissions_to_create = [
        (ct_product, 'add_product', 'Can add product'),
        (ct_product, 'change_product', 'Can change product'),
        (ct_product, 'delete_product', 'Can delete product'),
        (ct_product, 'view_product', 'Can view product'),
        (ct_category, 'view_category', 'Can view category'),
        (ct_order, 'view_order', 'Can view order'),
        (ct_order, 'change_order', 'Can change order'),
    ]
    for ct, codename, name in permissions_to_create:
        Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={'name': name}
        )

    # Назначаем права группам
    seller_group = Group.objects.get(name='Продавцы')
    seller_perms = Permission.objects.filter(
        codename__in=['add_product', 'change_product', 'delete_product', 'view_product', 'view_category']
    )
    seller_group.permissions.set(seller_perms)

    manager_group = Group.objects.get(name='Менеджер')
    manager_perms = Permission.objects.filter(
        codename__in=['view_order', 'change_order']
    )
    manager_group.permissions.set(manager_perms)

    # Создаём суперпользователя (администратора)
    if not User.objects.filter(username='admin').exists():
        admin = User.objects.create_superuser(
            username='admin',
            email='admin@gmail.com',
            password='admin'
        )
        admin.groups.add(manager_group, seller_group)

def reverse_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    Permission = apps.get_model('auth', 'Permission')
    # Удаляем назначения прав
    for group in Group.objects.filter(name__in=['Менеджер', 'Клиент', 'Продавцы']):
        group.permissions.clear()
    Group.objects.filter(name__in=['Менеджер', 'Клиент', 'Продавцы']).delete()
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('app_users', '0001_initial'),
        ('catalog', '0001_initial'),
        ('order', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(add_required_data, reverse_data),
    ]