# Generated by Django 6.0.3 on 2026-04-14 10:35

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ordering_index', models.IntegerField(default=0, verbose_name='Индекс сортировки')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Возможны подкатегории от главной категории товаров (макс 2 уровня)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Главная категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['ordering_index', 'name'],
            },
            bases=(catalog.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание товара')),
                ('short_description', models.TextField(verbose_name='Краткое описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_limited', models.BooleanField(default=False, help_text='В Limited edition попадают до 16 товаров с галочкой Ограниченный тираж', verbose_name='Ограниченный тираж')),
                ('ordering_index', models.IntegerField(default=0, help_text='В каталог топ-товаров попадают 8 первых товаров по параметру индекс сортировки', verbose_name='Индекс сортировки')),
                ('purchase_count', models.IntegerField(default=0, help_text='Товары сортируются по популярности', verbose_name='Количество покупок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-ordering_index', '-purchase_count'],
            },
            bases=(catalog.models.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
